version: '3.4'
services:
  puppeteer:
    image: morawskim/packtpub-free-learning:0.4.1
    restart: on-failure
    environment:
      TZ: Europe/Warsaw
      CRON_EXPRESSION: 40 7 * * *
    env_file:
      - .env-sensi
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 5s
# vim: ft=docker-compose.yaml:
